services:
  # --- BACKEND ---
  gamifyme-api:
    image: ghcr.io/frogames/gamifyme-api:latest
    container_name: gamifyme-api
    restart: always
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - Jwt__Key=${Jwt__Key}
      - Smtp__Host=${SMTP_HOST}
      - Smtp__Port=${SMTP_PORT}
      - Smtp__SenderEmail=${SMTP_SENDER_EMAIL}
      - Smtp__Password=${SMTP_PASSWORD}

  # --- FRONTEND ---
  gamifyme-web:
    image: ghcr.io/frogames/gamifyme-web:latest
    container_name: gamifyme-web
    restart: always
    ports:
      - "5001:8080" # On expose le 5001 localement
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # L'URL interne pour le SSR (Server Side Rendering)
      - ApiBaseUrl=http://gamifyme-api:8080
    depends_on:
      gamifyme-api:
        condition: service_started